services:

  db:
    image: postgres:13.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_socket:/var/run/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dracula-theme
    restart: unless-stopped

  adminer-dracula:
    image: bergalath/adminer-dracula:4.8.0-4
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - pg_socket:/var/run/postgresql
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_PLUGINS: tables-filter
      ADMINER_DEFAULT_USER: postgres
      ADMINER_DEFAULT_SERVER: postgresql:///var/run/postgresql
    restart: unless-stopped

volumes:
  pg_data:
  pg_socket:
