services:

  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dracula-theme

  adminer-dracula:
    image: bergalath/adminer-dracula:4.8.0-1
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_SERVER: db
